version: "3.9"
services:
  lama-flask:
    build: ../backend
    container_name: lama-flask
    environment:
      - HOST=lama-mysql
      - USER=lamaUser
      - PASSWORD=password
    links: 
      - lama-mysql
    depends_on:
      lama-mysql:
        condition: service_healthy
    ports:
      - 5000:5000

  lama-mysql:
    image: mysql:8-oracle
    container_name: lama-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: lama
      MYSQL_USER: lamaUser
      MYSQL_PASSWORD: password
    volumes:
      - mysqlData:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  lama-phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: lama-phpmyadmin
    links:
      - lama-mysql
    environment:
      PMA_HOST: lama-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 81:80
    depends_on:
      lama-mysql:
        condition: service_healthy

volumes:
  mysqlData:


# TODOs
# Move all the environment variables to here
# Make a network
# Do something about the volumes. Preferably I would want these to be stored in the root directory or something so everything stays nice and close.
# Perhaps fiddle with the health check. Currently the healthcheck takes over 20s which is super long because the first health check always fails.