version: "3.9"
services:
  lama-frontend:
    container_name: lama-frontend
    build: ../frontend
    depends_on:
      lama-backend: 
        condition: service_healthy
      lama-mysql:
        condition: service_healthy

  lama-backend:
    build: ../backend
    container_name: lama-backend
    environment:
      - HOST=lama-mysql
      - USER=lamaUser
      - PASSWORD=password
    links: 
      - lama-mysql
    depends_on:
      lama-mysql:
        condition: service_healthy

  lama-mysql:
    image: mysql:8-oracle
    container_name: lama-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: lama
      MYSQL_USER: lamaUser
      MYSQL_PASSWORD: password
    volumes:
      - mysqlData:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  lama-phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: lama-phpmyadmin
    links:
      - lama-mysql
    environment:
      PMA_HOST: lama-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: http://localhost/pma
    depends_on:
      lama-mysql:
        condition: service_healthy

  lama-nginx:
    build: ../nginx
    container_name: lama-nginx
    links:
      - lama-frontend
      - lama-backend
      - lama-phpmyadmin
    environment:
      hostname: lamahost.win.tue.nl
      letsencrypt: true
    depends_on:
      - lama-frontend
      - lama-backend
      - lama-mysql
      - lama-phpmyadmin
    ports:
          - 80:80
          - 443:443
volumes:
  mysqlData:


# TODOs
# Move all the environment variables to here
# Make a network
# Do something about the volumes. Preferably I would want these to be stored in the root directory or something so everything stays nice and close.
# Perhaps fiddle with the health check. Currently the healthcheck takes over 20s which is super long because the first health check always fails.